use_frameworks!
platform :ios, '13.0'
inhibit_all_warnings!

target 'GodEye_Example' do
  pod 'GodEye', :path => '../'

  target 'GodEye_Tests' do
    inherit! :search_paths

    post_install do |installer|
      installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
              end
          end
      end
    end
  end
end
